### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by kendall-beaver** [INFO-523-Exercises/project-final-The-Null-Wranglers#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Riyanshi - @riyanshibohra
- Dhanya - @SaiDhanyaa
- Ajinkya - @ajinkyapdeshmukh10
- Kendall - @kendallbeaver
- Udit - @uditChaudhary242

- Describe the goal of the project.

The goal/objective section is missing from their proposal. It would be better if they added a section to simply explain this to the reader/audience.

- Describe the data used or collected.

1. There is no source for the dataset and no information where the data is collected from.
2. The timeframe range is unclear (1819 - 1820? or 1919 - 1920? or 2019 - 2020?)
3. The column description for all 23 variables from their dataset provides a good description.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

It appears they will perform anomaly-based detection, time-series, and predictive analysis.

- Is there anything that is unclear from the proposal?

1. The idea and thought process is good, but we are unable to anlayze what they are going to predict out of the 23 variables.
2. It's clear what types of analysis methods they will be using with the data, but when it comes to making a prediction or anomaly-based prediction it's unclear how the group will be performing their assessments.

- Provide constructive feedback on how the team might be able to improve their project.

1. Create a section for the overall goal.
2. Be clear about what variables they'll use for the prediction analysis and how far out they'll be predicting (2 years? 5 years? etc.).
3. Add some visualization analysis (plots, graphs) to provide a better understanding of the data.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

1. Analyzing the academic performance before, during, and after COVID is actually an interesting topic and project.
2. The dataset is very comprehensive.
3. They are using more than one method in their analysis.

- Provide constructive feedback on any issues with file and/or code organization.

There is no "repo organization" section mentioned in their proposal.

- (Optional) Any further comments or feedback?

Overall the project is an interesting topic which includes a very comprehensive dataset and they will be using many different methods, but the project will benefit more by being more specific about the target variables for the predictive modeling.

**Comment by Rohit-Hemaraja** [comment]
I want to express my appreciation for the thought and effort you've put into our project proposal. Showcasing your review commitment in analyzing academic performance before, during, and after COVID is not only relevant but also intriguing.

We would acknowledge your review on our use of multiple methods, including anomaly-based detection, time-series, and predictive analysis, showcasing a thoughtful approach to addressing the research question.
