### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by ramdheeraj-uoa** [INFO-523-Exercises/project-final-The-Null-Wranglers#2]
The following is the peer review of the project proposal by [Data Diggers]. The team members that participated in this review are 

Ram Dheeraj Kamarajugadda - @ramdheeraj-uoa
Daniel Shevelev - @shahmatyUA
Kashyap Sai Prasad Nadendla - @KashyapNadendla
Shreya Kolte - @shreyakolte
Abhishek Deore - @abhishekdeore

- Describe the goal of the project.

The goal of the project wasn't mentioned at the beginning . Yet, we figured out from the questions that the goal is to develop a predictive model that accurately forecasts grade outcomes based on course attributes.

- Describe the data used or collected.

 The DEW counts data set contains information about the breakdown of grade value outcomes during the academic years of 18-19, 19-20, and 20-21. There are 23 attributes, Few of these are: College,Department,Subject.Code,Catalog.Number,Course.Description,Course.Level.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The approach to answer the research question is by examining the grade value outcomes for the years before, during and after the pandemic. The analysis will breakdown the grade values outcomes by college, department, division level and course level using clustering and classification techniques. Anomalies will be isolated for a more fine grained inspection that includes course attributes. These attributes will be used in an effort to create a predictive model .

- Is there anything that is unclear from the proposal?

The Project goal isn't specified at the beginning. The significant variables that are going to be used for the model training aren't specified. The analysis plan looks unclear as the weekly plan of attack was provided under it instead of the required steps for analysis.

- Provide constructive feedback on how the team might be able to improve their project.

1.The website is not being rendered on the github.
2. The whole dataset was mentioned in the proposal , which  is unnecessary, instead it is suggested to provide why that particular dataset is taken.
3.The analysis plan can be more descriptive and the weekly plan of action should be separately mentioned.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are interested in knowing the evaluation results of time series analysis ,decision tree analysis and the Predictive Model.
We would like to see the project objective highlighted in the proposal.

- Provide constructive feedback on any issues with file and/or code organization.

Code organization isn't provided in the proposal.

- (Optional) Any further comments or feedback?

Looking forward to see how the project turns out .

**Comment by Rohit-Hemaraja** [comment]
Dear Data Diggers Team,

I appreciate the thorough and constructive feedback provided in the peer review of our project proposal. It's evident that the reviewers took the time to carefully assess various aspects of your project and offer valuable insights for improvement.

I particularly commend the team for their attention to detail in highlighting areas that require clarification, such as the explicit mention of the project goal at the beginning, specifying significant variables for model training, and improving the clarity of the analysis plan.
