### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by riyanshibohra** [INFO-523-Exercises/project-final-The-Null-Wranglers#4]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

- Riyanshi Bohra - @riyanshibohra
- Kendall Beaver - @kendallbeaver
- Udit Chaudhary - @uditChaudhary242
- DhanyaPriya Somasundaram - @SaiDhanyaa
- Ajinkya Deshmukh - @ajinkyapdeshmukh10

- Content: Is the research question well designed and is the data being used relevant to the research question?
The question has been well designed overall and the data is used relevantly for the questions. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, they chose good visualizations and didn't oversaturate their presentation with too many graphs, but some of the graphs were unreadable and the members did read through the graphs a little too fast. Overall, though, the visualizations were great for the project.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
The initial idea seemed well-thought out, but the idea of analyzing grades before, during and after COVID did seem a bit cliched. As the group mentioned, having additional data for online performance and possibly looking at other departments may have improved the project. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Some plots had extra space and could have been compressed to focus on the line graphs; in addition a plot had a y-axis that was unreadable. But the group did have some plots that were readable and well-formatted. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Some members were prepared and some members read from slides, but overall they had practiced their presentation beforehand. The group fully answered the class's questions.

**Comment by kmanasil** [comment]
Thank you for your feedback. We have addressed these issues.
