### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by shreyakolte** [INFO-523-Exercises/project-final-The-Null-Wranglers#6]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members who participated in this review are 

- [Shreya Kolte] - @[shreyakolte]
- [Abhishek Deore] - @[abhishekdeore]
- [Daniel Shevelev] - @[shahmatyUA]
- [Ram Dheeraj Kamarajugadda] - @[ramdheeraj-uoa]
- [Kashyap Nadendla] - @[KashyapNadendla]

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, the research question was pretty well answered and well presented by the team members. The team used two datasets which were relevant and the team also mentioned that they needed more data for gaining more accuracy on the results.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
The explanations for the visualizations were rushed, making it challenging to grasp the interpretation of the visualization results. Too many tables were shown making it difficult to understand the outcomes.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes, it is evident that the project was implemented and planned very well by the team members. The limitations of having less data for analysis were also considered. The analysis was well done and led to the team finding out that the 2 variables 'online class' and 'second half' were used in the model for multilinear and lasso regression.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides were well organized and it was easy understand except the tables and visualizations that were explained pretty quickly.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project? 
A team effort was seen while presenting and each team member spoke well in their part and had a different module to speak about. Most of them were not reading from a script, otherwise, the project was well presented.

**Comment by kmanasil** [comment]
Thank you for your feedback. We have addressed these issues.
